base_url = "https://www.danielyrovas.com"
title = "danielyrovas"

compile_sass = false
build_search_index = false
generate_feed = true

taxonomies = [
  { name = "tags", feed = true }
]

[markdown]
highlight_code = true

[permalinks]
notes = "{parent}/{slug}/"

[extra]
author = "Daniel Savory"
home_notes_number = 1
home_posts_number = 1

nav = [
  { name = "Home", path = "/" },
  # { name = "Writing", path = "/posts/" },
  { name = "Notes", path = "/notes/" },
]
